name: Update Social Preview

on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  build-and-screenshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate new social-preview.png
        run: npm run generate-preview

      - name: Commit & push updated image
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/social-preview.png
          if ! git diff --staged --quiet; then
            git commit -m "chore: auto-update social preview"
            git push
          else
            echo "No changes to social-preview.png"
          fi
